/** Mapping des compétences typiques par secteur */
export const SECTOR_SKILLS: Record<string, string[]> = {
  IT: [
    'Java',
    'Python',
    'JavaScript',
    'TypeScript',
    'Angular',
    'React',
    'Vue.js',
    'Spring Boot',
    'Node.js',
    'Express.js',
    'Django',
    'FastAPI',
    'Docker',
    'Kubernetes',
    'Git',
    'GitHub Actions',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'REST API',
    'GraphQL',
    'CI/CD',
    'AWS',
    'Azure',
    'GCP',
    'DevOps',
    'Linux',
    'Terraform',
    'Microservices',
    'Cybersécurité',
    'Machine Learning',
    'Data Analysis',
    'Agile / Scrum',
  ],
  HEALTH: [
    'Diagnostic médical',
    'Soins infirmiers',
    'Pharmacologie',
    'Radiologie',
    'Chirurgie',
    'Anesthésie',
    'Santé mentale',
    'Gestion de patient',
    'Premiers secours',
    'EHPAD',
    'Stérilisation',
    'Prévention',
    'Traçabilité',
    'Réglementation sanitaire',
    'Télémédecine',
    'Ergonomie médicale',
    'Suivi des dossiers médicaux (DPI)',
    'Hygiène hospitalière',
    'Pédiatrie',
    'Gériatrie',
  ],
  BTP: [
    'Maçonnerie',
    'Charpente',
    'Plomberie',
    'Électricité',
    'Carrelage',
    'Peinture',
    'Menuiserie',
    'Gros œuvre',
    'Finitions',
    'Sécurité du chantier (HSE)',
    'Lecture de plans',
    'Devis',
    'Gestion de projet',
    'AutoCAD',
    'BIM (Revit)',
    'Étude de prix',
    'Topographie',
    'Isolation thermique',
    'Génie civil',
  ],
  COMMERCE: [
    'Vente',
    'Relation client',
    'Merchandising',
    'Gestion de caisse',
    'Négociation',
    'Fidélisation',
    'Multicanal',
    'E-commerce',
    'Marketing digital',
    'Gestion de stock',
    'Visual merchandising',
    'CRM',
    'Prospection commerciale',
    'Gestion du point de vente',
    'Cross-selling / Up-selling',
    'Gestion des réclamations',
  ],
  TRANSPORT: [
    'Permis poids lourd (C/EC)',
    'Permis marchandises',
    'Sécurité routière',
    'Tachygraphe',
    'Navigation GPS',
    'Logistique',
    'Chargement/déchargement',
    'Mécanique véhicule',
    'Respect des délais',
    'Itinéraires',
    'Transport de matières dangereuses (ADR)',
    'Conduite éco-responsable',
    'Gestion de flotte',
  ],
  EDUCATION: [
    'Pédagogie',
    'Enseignement',
    'Préparation de cours',
    'Évaluation',
    'Gestion de classe',
    'Accompagnement individuel',
    'Didactique',
    'Orientation',
    'Relation parents',
    'LMS (Canvas, Moodle)',
    'Inclusion scolaire (EBEP)',
    'E-learning',
    'Création de supports pédagogiques',
  ],
  ADMIN: [
    'Bureautique',
    'Gestion administrative',
    'Comptabilité de base',
    'Dossiers RH',
    'Archivage',
    'Secrétariat',
    'Gestion de planning',
    'Gestion du courrier',
    'SAP',
    'Accueil physique et téléphonique',
    'Rédaction de comptes-rendus',
    'Pack Office (Word, Excel, PowerPoint)',
    'Gestion des commandes fourniture',
  ],
  FINANCE: [
    'Comptabilité générale',
    'Comptabilité analytique',
    'Audit',
    'Consolidation',
    'Trésorerie',
    'Paie',
    'Reporting',
    'Normes IFRS',
    'Excel avancé',
    'SAP',
    'Business Objects',
    'Fiscalité',
    'Contrôle de gestion',
    'Analyse financière',
    'Gestion des risques',
    'Modélisation financière',
  ],
  HR: [
    'Recrutement',
    'Onboarding',
    'GPEC / GEPP',
    'Paie',
    'Droit du travail',
    'Formation',
    'Compensation & Benefits',
    'Relations sociales',
    'Talent management',
    'Succession planning',
    'ATS (Greenhouse, Workday)',
    'Marque employeur',
    'QVT (Qualité de Vie au Travail)',
  ],
  MARKETING: [
    'Marketing digital',
    'SEO',
    'SEM / Google Ads',
    'Social media',
    'Content marketing',
    'Email marketing',
    'Google Analytics',
    'Branding',
    'Marketing automation',
    'Growth hacking',
    'Copywriting',
    'Adobe Creative Suite',
    'Inbound marketing',
    'Étude de marché',
    'A/B Testing',
  ],
  SALES: [
    'Vente B2B',
    'Vente B2C',
    'Prospection téléphonique / Cold Email',
    'Négociation',
    'Closing',
    'CRM (Salesforce, HubSpot)',
    'Présentation client',
    'Fidélisation',
    'Commissioning',
    'Territory management',
    'Forecasting',
    'Social selling (LinkedIn)',
    'Key Account Management',
  ],
  LOGISTICS: [
    'Gestion de stock',
    'Préparation de commandes',
    'Manutention',
    'Optimisation d\'itinéraires',
    'TMS (Transport Management System)',
    'WMS (Warehouse Management System)',
    'Emballage',
    'Traçabilité',
    'Douane',
    'Incoterms',
    'CACES (Conduite d\'engins)',
    'Supply Chain',
    'Inventaire',
  ],
  HOTEL: [
    'Accueil',
    'Réception',
    'Housekeeping',
    'Room service',
    'Gestion de réservation',
    'Service client',
    'Sommellerie',
    'Protocole',
    'Langues étrangères',
    'PMS (Opera, Cloudbeds)',
    'Yield Management / Revenue Management',
    'Check-in / Check-out',
  ],
  RESTAURATION: [
    'Service en salle',
    'Cuisine',
    'Plonge',
    'Normes HACCP',
    'Bar / Mixologie',
    'Gestion des fiches techniques',
    'Gestion des stocks alimentaires',
    'Dressage des assiettes',
    'Prise de commande',
  ],
  TOURISM: [
    'Guide touristique',
    'Conception de séjours',
    'Relation agence',
    'Connaissance destination',
    'Langues étrangères',
    'Animation',
    'Gestion de groupe',
    'Sécurité',
    'Booking / Réservation',
    'Commentaires culturels',
    'E-tourisme',
  ],
  ENGINEERING: [
    'Conception mécanique',
    'Génie électrique',
    'Automatisme',
    'SolidWorks / CATIA',
    'Gestion de projet industriel',
    'Dimensionnement',
    'Gestion de la qualité (ISO 9001)',
    'R&D',
    'Lean Manufacturing',
    'Six Sigma',
  ],
  LEGAL: [
    'Droit des affaires',
    'Droit social',
    'Rédaction de contrats',
    'Veille juridique',
    'Contentieux',
    'Conformité / Compliance (RGPD)',
    'Propriété intellectuelle',
    'Conseil juridique',
  ],
  CREATIVE_DESIGN: [
    'UI Design',
    'UX Design',
    'Figma',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'Motion Design',
    'Design System',
    'Wireframing',
    'Prototypage',
  ],
  REAL_ESTATE: [
    'Prospection immobilière',
    'Estimation de bien',
    'Mandat de vente',
    'Gestion locative',
    'Droit immobilier',
    'Visite de biens',
    'Négociation immobilière',
  ],
  OTHER: [
    'Communication',
    'Travail d\'équipe',
    'Résolution de problèmes',
    'Adaptabilité',
    'Leadership',
    'Gestion du temps',
    'Pensée critique',
    'Créativité',
  ],
};


export function getSectorSkills(sector?: string | null): string[] {
  if (!sector) return SECTOR_SKILLS['OTHER'] || [];
  return SECTOR_SKILLS[sector] || SECTOR_SKILLS['OTHER'] || [];
}