spring.application.name=jobradar

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobradar
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Serveur
server.port=8080

# JWT
jobradar.jwt.secret=maCleSecreteSuperLongueDeAuMoins256BitsPourEviterLesProblemesDeSecurite123456
jobradar.jwt.expiration=86400000

# Logs
logging.level.jobradarbackend.jobradar=DEBUG
# ============================================================
# API France Travail
# ============================================================
francetravail.client-id=PAR_jobradar_71eec9840e021874ab4e00369fd660af36a372015c4897b22ae42137c00de722
francetravail.client-secret=39f3885e3c51b35ad5b2cc5953705d17bc5f87c7bc91197f9db1c9b7f8e5265d
francetravail.token-url=https://entreprise.francetravail.fr/connexion/oauth2/access_token?realm=/partenaire
francetravail.offers-url=https://api.francetravail.io/partenaire/offresdemploi/v2/offres/search
francetravail.scopes=api_offresdemploiv2 o2dsoffre